version: '3'

services:

  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
    ports:
      - "3308:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql